export const API_BASE_URL = import.meta.env.VITE_BASE_URL;
export const API_ROUTES = {
  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  REFRESH: "/auth/refresh",
  LOGOUT: "/auth/logout",
  GET_PROFILE: "/users/profile",
  UPDATE_USER: "/users/update",
  DELETE_USER: "/users/delete",
  GET_ALL_USERS: "/users",
  SEARCH_USER: "/users/search",
  CREATE_POST: "/posts",
  GET_All_POSTS: "/posts",
  GET_FRIEND_LIST: "/friends/myfriends",
  SEND_FRIEND_REQUEST: "/friends/request",
  GET_FRIEND_REQUESTS: "/friends/incoming",
  RESPOND_FRIEND_REQUEST: "/friends/respond",
  GET_SINGLE_MESSAGES: "/chat",
  SEND_SINGLE_MESSAGES: "/chat/send",
  GET_POST_BY_ID: (id) => `/post/${id}`,
  UPDATE_POST: (id) => `/post/update/${id}`,
  DELETE_POST: (id) => `/post/delete/${id}`,
};
